<?php
/* @var \Magento\Framework\View\Element\Html\Links $this */

$html = '';
if ($this->getLinks()) {
    $html .= ($this->hasCssClass() ? '
    <style>
    .prxgtTopWindow {
    position: fixed;
    top: 0;
    z-index:9999;
    }
    @media only screen and (min-width: 768px) {
        .prxgt-footer-links-block {
            padding-bottom: 140px;
            display: block;
        }
        .prxgt-footer-links-small-size-block {
            padding-bottom: 140px;
            display: none;
        }
        .prxgt-footer-links {
            float: left;
            margin-right: 1.5%;
            width: 15%;
        }
    }
    @media only screen and (max-width: 767px) {
        .prxgt-footer-links-block {
            display: none;
        }
        .prxgt-footer-links-small-size-block {
            display: block;
        }
        .prxgt-footer-links {
            width: 100%;
        }
    }
    </style>' : '');
    $html .= '
<script type="text/javascript">
    $(document).ready(function () {
        var objToStick = $("#prxgt-footer-links-block"); //Получаем нужный объект
        var topOfObjToStick = $(objToStick).offset().top; //Получаем начальное расположение нашего блока

        $(window).scroll(function () {
            var windowScroll = $(window).scrollTop(); //Получаем величину, показывающую на сколько прокручено окно

            if (windowScroll > topOfObjToStick) { // Если прокрутили больше, чем расстояние до блока, то приклеиваем его
                $(objToStick).addClass("prxgtTopWindow");
            } else {
                $(objToStick).removeClass("prxgtTopWindow");
            };
        });
    });
</script>';
    $column[1] = '';
    $column[2] = '';
    $column[3] = '';
    $column[4] = '';
    $columnSmallSize[1] = '';
    $columnSmallSize[2] = '';
    $columnSmallSize[3] = '';
    $columnSmallSize[4] = '';

    $column[1] = '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . '>';
    $column[2] =  '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . '>';
    $column[3] = '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . '>';
    $column[4] = '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . '>';

    $columnSmallSize[1] = '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . ' data-role="content">';
    $columnSmallSize[2] =  '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . ' data-role="content">';
    $columnSmallSize[3] = '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . ' data-role="content">';
    $columnSmallSize[4] = '<ul' . ($this->hasCssClass() ? ' class="' . $this->escapeHtml(
                $this->getCssClass()
            ) . '"' : '') . ' data-role="content">';
    $i = 0;
    foreach ($this->getLinks() as $link) {
        $column[(int)($i % 4) + 1] .= $this->renderLink($link);
        $columnSmallSize[(int)($i % 4) + 1] .= $this->renderLink($link);
        $i++;
    }
    $column[1] .= '</ul>';
    $column[2] .= '</ul>';
    $column[3] .= '</ul>';
    $column[4] .= '</ul>';

    $columnSmallSize[1] .= '</ul>';
    $columnSmallSize[2] .= '</ul>';
    $columnSmallSize[3] .= '</ul>';
    $columnSmallSize[4] .= '</ul>';

    $html .=
        '<div class="prxgt-footer-links-block" id="prxgt-footer-links-block"> <div class="prxgt-footer-links"><h4>Privacy</h4>'.$column[1].'</div>'.
        '<div class="prxgt-footer-links"><h4>Search</h4>'.$column[2].'</div>'.
        '<div class="prxgt-footer-links"><h4>Contacts</h4>'.$column[3].'</div>'.
        '<div class="prxgt-footer-links"><h4>Orders</h4>'.$column[4].'</div> </div>';
    $html .=
        '<div class="prxgt-footer-links-small-size-block"> <div class="prxgt-footer-links" data-mage-init=\'{"collapsible":{ "active": false, "animate": 200, "collapsible": true}}\' ><div data-role="title"><h4><a href="#">Privacy</a></h4></div>'.$columnSmallSize[1].'</div>'.
        '<div class="prxgt-footer-links" data-mage-init=\'{"collapsible":{ "active": false, "animate": 200, "collapsible": true}}\' ><div data-role="title"><h4><a href="#">Search</a></h4></div>'.$columnSmallSize[2].'</div>'.
        '<div class="prxgt-footer-links" data-mage-init=\'{"collapsible":{ "active": false, "animate": 200, "collapsible": true}}\' ><div data-role="title"><h4><a href="#">Contacts</a></h4></div>'.$columnSmallSize[3].'</div>'.
        '<div class="prxgt-footer-links" data-mage-init=\'{"collapsible":{ "active": false, "animate": 200, "collapsible": true}}\' ><div data-role="title"><h4><a href="#">Orders</a></h4></div>'.$columnSmallSize[4].'</div> </div>';
}

echo $html;
